name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk unzip git
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK & NDK
        run: |
          sudo apt install -y wget
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d $HOME/.buildozer/android/platform
          yes | $HOME/.buildozer/android/platform/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: robot-trading-apk
          path: bin/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
